[project]
name = "Chatterbot"
version = "0.0.2"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "numpy==1.26.4",
    "tomli_w==1.2.0",
    "pydantic>=2.10.6",
    "setuptools==76.0.0",
    "streamlit==1.43.2",
    "streamlit-antd-components==0.3.2",
    "openai>=1.82.0",
    "httpx[http2,socks]>=0.28.1",
    "dotenv>=0.9.9",
    "aiohttp>=3.12.7",
    "aiofiles>=24.1.0",
    "websockets>=15.0.1",
    "sherpa-onnx>=1.12.1",
    "sounddevice>=0.5.2",
    "pexpect>=4.9.0",
    "pvporcupinedemo>=3.0.5",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
    "soundfile>=0.13.1",
    "rpi-ws281x>=5.0.0; platform_machine=='armv7l' or platform_machine=='aarch64'",
    "rpi-gpio>=0.7.1; platform_machine=='armv7l' or platform_machine=='aarch64'",
]
authors = [{ name = "MrXnneHang", email = "XnneHang@gmail.com" }]


[project.scripts]
test-openai = "chatbot.tests.test_openai:main"
test-workflow = "chatbot.tests.test_openai_workflow:main" 
test-spotter = "chatbot.tests.test_spotter_keyword:main"
test-gpio = "chatbot.tests.test_gpio:main"
test-wakeup = "chatbot.tests.test_porcupine_kws:main"
play-audio = "chatbot.tests.test_play_audio:main"
models = "chatbot.list_model_name:main"

[dependency-groups]
dev = [
  "pyright>=1.1.391",
  "ruff>=0.9.3",
  "pytest>=8.3.4",
  "pytest-rerunfailures>=15.0",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118", marker = "sys_platform == 'win32'" }, # sys_platform : 'win32' , 'linux' , 'Darwin'
  { index = "pytorch-cpu", marker = "sys_platform != 'win32'"}
]
torchaudio = [
  { index = "pytorch-cu118", marker = "sys_platform == 'win32'" },
  { index = "pytorch-cpu", marker = "sys_platform != 'win32'"}
]

[tool.pyright]
include = ["src/chatbot","tests"]
pythonVersion = "3.11"
typeCheckingMode = "strict"
reportMissingTypeStubs = false

[tool.ruff]
line-length = 120
target-version = "py311"



[tool.ruff.lint]
select = [
  # Pyflakes
  "F",
  # Pycodestyle
  "E",
  "W",
  # Isort
  "I",
  # Comprehensions
  "C4",
  # Debugger
  "T100",
  # Pyupgrade
  "UP",
  # Flake8-pyi
  "PYI",
  # Bugbear
  "B",
  # Pylint
  "PLE",
  # Flake8-simplify
  "SIM101",
  # Flake8-use-pathlib
  "PTH",
  # Pygrep-hooks
  "PGH004",
  # Flake8-type-checking
  "TC",
  # Flake8-raise
  "RSE",
  # Refurb
  "FURB",
  # Flake8-future-annotations
  "FA",
  # Yesqa
  "RUF100",
]
ignore = [
  "E501", # line too long, duplicate with ruff fmt
  "F401", # imported but unused, duplicate with pyright
  "F841", # local variable is assigned to but never used, duplicate with pyright
]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
known-first-party = ["chatbot"]
combine-as-imports = true

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]


[tool.hatch.build.targets.wheel]
packages = ["src/chatbot"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# 选取的该版本 Pytorch 仅仅支持 310 311.
# < 3.11 需要额外安装 tomlilib 
# < 3.11 不支持 *tuple 的解包。(_dataclass.py 中涉及)
# 于是，该项目只能在 3.11 运行，3.12 及以上需要考虑手动升级 pytorch。
