sdk_base_url = "sdk_base_url"
sdk_key = "sdk_key"
vits_split_url = "http://localhost:7900/tts/split"
vits_direct_url = "http://localhost:7900/tts/direct"
asr_url = "http://localhost:8000/rec-audio"
vad_url = "http://localhost:8000/vad-audio"
cache_dir = "cache"
access_key = "access_key"
